{
 "title": "Weekly Bug Retro",
 "tags": [
  "Engineering Leads Dashboard",
  "Highlights"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "board_id",
    "label": "Board",
    "query": "select concat(name, '-', id) as text from boards"
   },
   {
    "name": "issue_type",
    "label": "Issue Type",
    "query": "select distinct type from issues"
   },
   {
    "name": "priority",
    "label": "Priority",
    "query": "select distinct priority from issues"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard can be used to track bugs with metrics such as [Bug Age](https://devlake.apache.org/docs/Metrics/BugAge).\n- Data Source Required: One of the issue tracking tools, e.g. [GitHub](https://devlake.apache.org/docs/UserManuals/ConfigUI/GitHub#step-3---adding-transformation-rules-optional), [GitLab](https://devlake.apache.org/docs/Configuration/GitLab) or [Jira](https://devlake.apache.org/docs/UserManuals/ConfigUI/Jira#step-3---adding-transformation-rules-optional) (Scope Config required to define which issues are bugs)."
   },
   "targets": [
    {}
   ]
  },
  { "title": "Overall Bug Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Weekly New Bugs [Selected Time Range]",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "with bugs as (  \n  select \n    DATE_ADD(date(i.created_date), INTERVAL -WEEKDAY(date(i.created_date)) DAY) as time,\n    count(distinct i.id) as bug_count\n  from\n    issues as i\n\t  join board_issues bi on i.id = bi.issue_id\n\t  join boards b on bi.board_id = b.id\n  where \n    i.type in (${issue_type})\n    and i.status != 'REJECTED'\n    and $__timeFilter(i.created_date)\n    and b.id in (${board_id})\n  group by time\n  order by time desc\n),\n\ncalendar_date as(\n\tSELECT CAST(($__timeTo()-INTERVAL (H+T+U) DAY) AS date) d\n\tFROM ( SELECT 0 H\n\t\t\tUNION ALL SELECT 100 UNION ALL SELECT 200 UNION ALL SELECT 300\n\t\t) H CROSS JOIN ( SELECT 0 T\n\t\t\tUNION ALL SELECT  10 UNION ALL SELECT  20 UNION ALL SELECT  30\n\t\t\tUNION ALL SELECT  40 UNION ALL SELECT  50 UNION ALL SELECT  60\n\t\t\tUNION ALL SELECT  70 UNION ALL SELECT  80 UNION ALL SELECT  90\n\t\t) T CROSS JOIN ( SELECT 0 U\n\t\t\tUNION ALL SELECT   1 UNION ALL SELECT   2 UNION ALL SELECT   3\n\t\t\tUNION ALL SELECT   4 UNION ALL SELECT   5 UNION ALL SELECT   6\n\t\t\tUNION ALL SELECT   7 UNION ALL SELECT   8 UNION ALL SELECT   9\n\t\t) U\n\tWHERE\n\t\t($__timeTo()-INTERVAL (H+T+U) DAY) >= ($__timeTo()-INTERVAL 6 MONTH)\n),\n\ncalendar_weeks as(\n  select \n  \tdistinct date(DATE_ADD(date(d), INTERVAL -WEEKDAY(date(d)) DAY)) as start_of_week\n  FROM calendar_date\n  ORDER BY 1 asc\n)\n\n\nselect \n  concat(date_format(cw.start_of_week,'%m/%d'), ' - ', date_format(DATE_ADD(cw.start_of_week, INTERVAL +7 DAY),'%m/%d')) as week,\n  case when bug_count is not null then bug_count else 0 end as 'Weekly New Bugs'\nfrom calendar_weeks cw left join bugs b on cw.start_of_week = b.time\norder by cw.start_of_week asc\n"
    }
   ]
  },
  {
   "title": "Weekly Closed Bugs [Selected Time Range]",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "with bugs as (\n  select \n    DATE_ADD(date(i.resolution_date), INTERVAL -WEEKDAY(date(i.resolution_date)) DAY) as time,\n    count(distinct i.id) as bug_count\n  from\n    issues as i\n\t  join board_issues bi on i.id = bi.issue_id\n\t  join boards b on bi.board_id = b.id\n  where \n    i.type in (${issue_type})\n    and status = 'DONE'\n    and i.status != 'REJECTED'\n    and $__timeFilter(i.resolution_date)\n    and b.id in (${board_id})\n  group by time\n  order by time desc\n),\n\ncalendar_date as(\n\tSELECT CAST(($__timeTo()-INTERVAL (H+T+U) DAY) AS date) d\n\tFROM ( SELECT 0 H\n\t\t\tUNION ALL SELECT 100 UNION ALL SELECT 200 UNION ALL SELECT 300\n\t\t) H CROSS JOIN ( SELECT 0 T\n\t\t\tUNION ALL SELECT  10 UNION ALL SELECT  20 UNION ALL SELECT  30\n\t\t\tUNION ALL SELECT  40 UNION ALL SELECT  50 UNION ALL SELECT  60\n\t\t\tUNION ALL SELECT  70 UNION ALL SELECT  80 UNION ALL SELECT  90\n\t\t) T CROSS JOIN ( SELECT 0 U\n\t\t\tUNION ALL SELECT   1 UNION ALL SELECT   2 UNION ALL SELECT   3\n\t\t\tUNION ALL SELECT   4 UNION ALL SELECT   5 UNION ALL SELECT   6\n\t\t\tUNION ALL SELECT   7 UNION ALL SELECT   8 UNION ALL SELECT   9\n\t\t) U\n\tWHERE\n\t\t($__timeTo()-INTERVAL (H+T+U) DAY) >= ($__timeTo()-INTERVAL 6 MONTH)\n),\n\ncalendar_weeks as(\n  select \n  \tdistinct date(DATE_ADD(date(d), INTERVAL -WEEKDAY(date(d)) DAY)) as start_of_week\n  FROM calendar_date\n  ORDER BY 1 asc\n)\n\nselect \n  concat(date_format(cw.start_of_week,'%m/%d'), ' - ', date_format(DATE_ADD(cw.start_of_week, INTERVAL +7 DAY),'%m/%d')) as week,\n  case when bug_count is not null then bug_count else 0 end as 'Weekly Closed Bugs'\nfrom calendar_weeks cw left join bugs b on cw.start_of_week = b.time\norder by cw.start_of_week asc"
    }
   ]
  },
  {
   "title": "Total Outstanding Bug Count by Week [Selected Time Range]",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "with calendar_date as(\n\tSELECT CAST(($__timeTo()-INTERVAL (H+T+U) DAY) AS date) d\n\tFROM ( SELECT 0 H\n\t\t\tUNION ALL SELECT 100 UNION ALL SELECT 200 UNION ALL SELECT 300\n\t\t) H CROSS JOIN ( SELECT 0 T\n\t\t\tUNION ALL SELECT  10 UNION ALL SELECT  20 UNION ALL SELECT  30\n\t\t\tUNION ALL SELECT  40 UNION ALL SELECT  50 UNION ALL SELECT  60\n\t\t\tUNION ALL SELECT  70 UNION ALL SELECT  80 UNION ALL SELECT  90\n\t\t) T CROSS JOIN ( SELECT 0 U\n\t\t\tUNION ALL SELECT   1 UNION ALL SELECT   2 UNION ALL SELECT   3\n\t\t\tUNION ALL SELECT   4 UNION ALL SELECT   5 UNION ALL SELECT   6\n\t\t\tUNION ALL SELECT   7 UNION ALL SELECT   8 UNION ALL SELECT   9\n\t\t) U\n\tWHERE\n\t\t($__timeTo()-INTERVAL (H+T+U) DAY) >= ($__timeTo()-INTERVAL 6 MONTH)\n),\n\ncalendar_weeks as(\n  select \n  \tdistinct date(DATE_ADD(date(d), INTERVAL -WEEKDAY(date(d)) DAY)) as start_of_week\n  FROM calendar_date\n  ORDER BY 1 asc\n),\n\ncreated_bugs as (  \n  select \n    DATE_ADD(date(i.created_date), INTERVAL -WEEKDAY(date(i.created_date)) DAY) as time,\n    count(distinct i.id) as bug_count\n  from\n    issues as i\n\t  join board_issues bi on i.id = bi.issue_id\n\t  join boards b on bi.board_id = b.id\n  where \n    i.type in (${issue_type})\n    and i.status != 'REJECTED'\n    and $__timeFilter(i.created_date)\n    and b.id in (${board_id})\n  group by time\n  order by time desc\n),\n\nresolved_bugs as (\n  select \n    DATE_ADD(date(i.resolution_date), INTERVAL -WEEKDAY(date(i.resolution_date)) DAY) as time,\n    count(distinct i.id) as bug_count\n  from\n    issues as i\n\t  join board_issues bi on i.id = bi.issue_id\n\t  join boards b on bi.board_id = b.id\n  where \n    i.type in (${issue_type})\n    and status = 'DONE'\n    and i.status != 'REJECTED'\n    and $__timeFilter(i.resolution_date)\n    and b.id in (${board_id})\n  group by time\n  order by time desc\n),\n\nweekly_new_bug as(\n  select\n    cw.start_of_week as week,\n    case when bug_count is not null then bug_count else 0 end as weekly_new_bug\n  from calendar_weeks cw left join created_bugs cb on cw.start_of_week = cb.time\n),\n\nweekly_closed_bug as(\n  select\n    cw.start_of_week as week,\n    case when bug_count is not null then bug_count else 0 end as weekly_closed_bug\n  from calendar_weeks cw left join resolved_bugs cb on cw.start_of_week = cb.time\n),\n\nweekly_updates as(\n  SELECT t1.week, weekly_new_bug, weekly_closed_bug FROM weekly_new_bug t1\n  LEFT JOIN weekly_closed_bug t2 ON t1.week = t2.week\n  UNION\n  SELECT t1.week, weekly_new_bug, weekly_closed_bug FROM weekly_new_bug t1\n  RIGHT JOIN weekly_closed_bug t2 ON t1.week = t2.week\n),\n\n\noriginal_open_bugs as (\n  SELECT \n    count(distinct i.id) as original_open_bug_count\n  FROM\n    issues as i\n\t  join board_issues bi on i.id = bi.issue_id\n\t  join boards b on bi.board_id = b.id\n  where \n    i.type in (${issue_type})\n    and i.status != 'REJECTED'\n    and i.created_date < $__timeFrom()\n    and (i.status != 'DONE' or $__timeFilter(i.resolution_date))\n    and b.id in (${board_id})\n),\n\nweekly_updated_without_null as(\n  SELECT \n    week, \n    COALESCE(weekly_new_bug,0) as weekly_new_bug, \n    COALESCE(weekly_closed_bug,0) as weekly_closed_bug,\n    original_open_bug_count\n  from weekly_updates, original_open_bugs\n  where week is not null\n),\n\nweekly_delta as(\n  SELECT \n    *,\n    (weekly_new_bug - weekly_closed_bug) as weekly_delta\n  from weekly_updated_without_null\n  order by week asc\n),\n\nfinal_data as(\n  SELECT \n    *,\n    concat(date_format(week,'%m/%d'), ' - ', date_format(DATE_ADD(week, INTERVAL +7 DAY),'%m/%d')) as _week,\n    sum(weekly_delta) over(order by week asc) as weekly_accumulated\n  from weekly_delta\n)\n\nSELECT \n  _week,\n  (original_open_bug_count + weekly_accumulated) as \"Total No. of Outstanding Bugs By the End of Week\" from final_data"
    }
   ]
  },
  { "title": "Detailed Bug Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Last Week's New Bug Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  count(distinct i.id)\nAS \"New Bugs\" from\n  issues as i\n  join board_issues bi on i.id = bi.issue_id\n  join boards b on bi.board_id = b.id\nwhere\n  i.type in (${issue_type})\n  and i.status != 'REJECTED'\n  and b.id in (${board_id})\n  AND i.created_date BETWEEN \n    DATE_SUB(FROM_UNIXTIME($__to / 1000), INTERVAL WEEKDAY(FROM_UNIXTIME($__to / 1000))+7 DAY)\n  AND \n    DATE_SUB(FROM_UNIXTIME($__to / 1000), INTERVAL WEEKDAY(FROM_UNIXTIME($__to / 1000)) DAY)"
    }
   ]
  },
  {
   "title": "Last Week's New Bug Count by Priority",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "targets": [
    {
     "rawSql": "select\n  priority,\n  count(distinct i.id) as 'Issue Number'\nfrom\n  issues as i\n  join board_issues bi on i.id = bi.issue_id\n  join boards b on bi.board_id = b.id\nwhere\n  i.type in (${issue_type})\n  and i.status != 'REJECTED'\n  and b.id in (${board_id})\n  AND i.created_date BETWEEN \n    DATE_SUB(FROM_UNIXTIME($__to / 1000), INTERVAL WEEKDAY(FROM_UNIXTIME($__to / 1000))+7 DAY)\n  AND \n    DATE_SUB(FROM_UNIXTIME($__to / 1000), INTERVAL WEEKDAY(FROM_UNIXTIME($__to / 1000)) DAY)\ngroup by 1"
    }
   ]
  },
  {
   "title": "Last Week's New Bugs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "select\n  i.issue_key as 'Issue Number',\n  i.title as 'Title',\n  i.url as 'Url',\n  i.creator_name as 'Creator'\nfrom\n  issues as i\n\tjoin board_issues bi on i.id = bi.issue_id\n\tjoin boards b on bi.board_id = b.id\nwhere\n  i.type in (${issue_type})\n  and i.status != 'REJECTED'\n  and b.id in (${board_id})\n  AND i.created_date BETWEEN \n    DATE_SUB(FROM_UNIXTIME($__to / 1000), INTERVAL WEEKDAY(FROM_UNIXTIME($__to / 1000))+7 DAY)\n  AND \n    DATE_SUB(FROM_UNIXTIME($__to / 1000), INTERVAL WEEKDAY(FROM_UNIXTIME($__to / 1000)) DAY)"
    }
   ]
  },
  {
   "title": "Last Week's Fixed Bugs Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  count(distinct i.id)\nAS \"Fixed Bugs\" from\n  issues as i\n  join board_issues bi on i.id = bi.issue_id\n\tjoin boards b on bi.board_id = b.id\nwhere\n  i.type in (${issue_type})\n  and status = 'DONE'\n  and i.status != 'REJECTED'\n  and b.id in (${board_id})\n  AND i.resolution_date BETWEEN \n    DATE_SUB(FROM_UNIXTIME($__to / 1000), INTERVAL WEEKDAY(FROM_UNIXTIME($__to / 1000))+7 DAY)\n  AND \n    DATE_SUB(FROM_UNIXTIME($__to / 1000), INTERVAL WEEKDAY(FROM_UNIXTIME($__to / 1000)) DAY)"
    }
   ]
  },
  {
   "title": "Average Lead Time of Last Week's Resolved Bugs in Days",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  avg(lead_time_minutes / 1440)\nAS \"Avg Lead Time (days)\" from\n  issues as i\n\tjoin board_issues bi on i.id = bi.issue_id\n\tjoin boards b on bi.board_id = b.id\nwhere\n  i.type in (${issue_type})\n  and status = 'DONE'\n  and i.status != 'REJECTED'\n  and b.id in (${board_id})\n  AND i.resolution_date BETWEEN \n    DATE_SUB(FROM_UNIXTIME($__to / 1000), INTERVAL WEEKDAY(FROM_UNIXTIME($__to / 1000))+7 DAY)\n  AND \n    DATE_SUB(FROM_UNIXTIME($__to / 1000), INTERVAL WEEKDAY(FROM_UNIXTIME($__to / 1000)) DAY)"
    }
   ]
  },
  {
   "title": "Last Week's Fixed Bugs",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "rawSql": "select\n  i.issue_key as 'Issue Number',\n  i.title as 'Title',\n  lead_time_minutes/1440 as 'Lead Time in Days',\n  i.url as 'Url'\nfrom\n  issues as i\n\tjoin board_issues bi on i.id = bi.issue_id\n\tjoin boards b on bi.board_id = b.id\nwhere\n  i.type in (${issue_type})\n  and status = 'DONE'\n  and i.status != 'REJECTED'\n  and b.id in (${board_id})\n  AND i.resolution_date BETWEEN \n    DATE_SUB(FROM_UNIXTIME($__to / 1000), INTERVAL WEEKDAY(FROM_UNIXTIME($__to / 1000))+7 DAY)\n  AND \n    DATE_SUB(FROM_UNIXTIME($__to / 1000), INTERVAL WEEKDAY(FROM_UNIXTIME($__to / 1000)) DAY)"
    }
   ]
  },
  {
   "title": "Top 10 Issue Lead Time [Last Week's Resolved Bugs in Days]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "select\n  concat('#',i.issue_key, ' ', i.title) as issue_key,\n  lead_time_minutes/1440 as lead_time\nfrom\n  issues as i\n\tjoin board_issues bi on i.id = bi.issue_id\n\tjoin boards b on bi.board_id = b.id\nwhere\n  i.type in (${issue_type})\n  and status = 'DONE'\n  and i.status != 'REJECTED'\n  and b.id in (${board_id})\n  AND i.resolution_date BETWEEN \n    DATE_SUB(FROM_UNIXTIME($__to / 1000), INTERVAL WEEKDAY(FROM_UNIXTIME($__to / 1000))+7 DAY)\n  AND \n    DATE_SUB(FROM_UNIXTIME($__to / 1000), INTERVAL WEEKDAY(FROM_UNIXTIME($__to / 1000)) DAY)\norder by lead_time desc\nlimit 10"
    }
   ]
  },
  {
   "title": "Total Number of Outstanding Bugs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  count(distinct i.id)\nAS \"Outstanding Bugs\" from \n  issues i\n\tjoin board_issues bi on i.id = bi.issue_id\n\tjoin boards b on bi.board_id = b.id\nwhere\n  i.type in (${issue_type})\n  and i.status NOT IN ('DONE', 'REJECTED')\n  and b.id in (${board_id})"
    }
   ]
  },
  {
   "title": "Average Age of Outstanding Bugs in Days",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  avg((TIMESTAMPDIFF(MINUTE, i.created_date,NOW()))/1440)\nAS \"Avg Age (days)\" from \n  issues i\n\tjoin board_issues bi on i.id = bi.issue_id\n\tjoin boards b on bi.board_id = b.id\nwhere\n  i.type in (${issue_type})\n  and i.status NOT IN ('DONE', 'REJECTED')\n  and b.id in (${board_id})"
    }
   ]
  },
  {
   "title": "Outstanding Bugs Sort by Queue Time [All History]",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "rawSql": "select \n  i.issue_key as 'Issue Number',\n  i.title as 'Title',\n  priority as 'Priority',\n  severity as 'Severity',\n  (TIMESTAMPDIFF(MINUTE, i.created_date,NOW()))/1440 as 'Queue Time in Days',\n  i.url as 'Url'\nfrom \n  issues i\n\tjoin board_issues bi on i.id = bi.issue_id\n\tjoin boards b on bi.board_id = b.id\nwhere\n  i.type in (${issue_type})\n  and i.status NOT IN ('DONE', 'REJECTED')\n  and b.id in (${board_id})\n  and priority in (${priority})\norder by (TIMESTAMPDIFF(MINUTE, i.created_date, NOW()))/1440 desc"
    }
   ]
  },
  {
   "title": "Top 100 Bug Queue Time in Days [Outstanding Bugs]",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "rawSql": "select \n  concat('#', i.issue_key) as issue_key,\n  (TIMESTAMPDIFF(MINUTE, i.created_date,NOW()))/1440 as 'Queue Time in Days'\nfrom \n  issues i\n\tjoin board_issues bi on i.id = bi.issue_id\n\tjoin boards b on bi.board_id = b.id\nwhere\n  i.type in (${issue_type})\n  and i.status NOT IN ('DONE', 'REJECTED')\n  and b.id in (${board_id})\norder by 2 desc\nlimit 100"
    }
   ]
  },
  {
   "title": "Bugs to be Triaged Sort by Queue Time [All History]",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "rawSql": "select \n  i.issue_key as 'Issue Number',\n  i.title as 'Title',\n  priority as 'Priority',\n  severity as 'Severity',\n  (TIMESTAMPDIFF(MINUTE, i.created_date,NOW()))/1440 as 'Queue Time in Days',\n  i.url as 'Url'\nfrom \n  issues i\n\tjoin board_issues bi on i.id = bi.issue_id\n\tjoin boards b on bi.board_id = b.id\nwhere\n  i.type in (${issue_type})\n  and i.status NOT IN ('DONE', 'REJECTED')\n  and i.assignee_name = ''\n  and b.id in (${board_id})\norder by (TIMESTAMPDIFF(MINUTE, i.created_date, NOW()))/1440 desc"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 76 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/UserManuals/Dashboards/GrafanaUserGuide)."
   },
   "targets": [
    {}
   ]
  }
 ]
}