/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package e2e

import (
	"testing"

	"github.com/apache/incubator-devlake/plugins/aidetector/tasks"
	"github.com/stretchr/testify/assert"
)

// Tests matching eng-product-metrics/tests/core/test_ai_detection.py

func TestDetectAIInText_EmptyReturnsNoDetection(t *testing.T) {
	result := tasks.DetectAIInText("")
	assert.False(t, result.Detected)
	assert.Empty(t, result.Tools)
	assert.Equal(t, 0, result.Confidence)
}

func TestDetectAIInText_DetectsClaudeCodeTrailer(t *testing.T) {
	text := `Fix authentication bug

Co-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>`
	result := tasks.DetectAIInText(text)
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "claude_code")
	assert.GreaterOrEqual(t, result.Confidence, 90)
}

func TestDetectAIInText_DetectsCopilotTrailer(t *testing.T) {
	text := `Add unit tests

Co-Authored-By: @copilot`
	result := tasks.DetectAIInText(text)
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "copilot")
	assert.GreaterOrEqual(t, result.Confidence, 90)
}

func TestDetectAIInText_DetectsClaudeCodeMarker(t *testing.T) {
	text := `## Summary
Added new feature

🤖 Generated with [Claude Code](https://claude.ai/claude-code)`
	result := tasks.DetectAIInText(text)
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "claude_code")
	assert.GreaterOrEqual(t, result.Confidence, 80)
}

func TestDetectAIInText_DetectsCursorMarker(t *testing.T) {
	result := tasks.DetectAIInText("Generated with Cursor")
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "cursor")
}

func TestDetectAIInText_DetectsCodexMarker(t *testing.T) {
	result := tasks.DetectAIInText("Generated by OpenAI Codex")
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "codex")
}

func TestDetectAIInText_DetectsGenericAIMarker(t *testing.T) {
	result := tasks.DetectAIInText("This code was AI-generated")
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "unknown")
	assert.Less(t, result.Confidence, 70) // Lower confidence for generic
}

func TestDetectAIInText_NoDetectionInRegularText(t *testing.T) {
	result := tasks.DetectAIInText("Fixed bug in authentication module")
	assert.False(t, result.Detected)
}

func TestDetectAIInText_CaseInsensitiveDetection(t *testing.T) {
	result := tasks.DetectAIInText("GENERATED WITH CLAUDE CODE")
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "claude_code")
}

func TestDetectAIInText_DetectsMultipleTools(t *testing.T) {
	text := `Fix bugs

Generated with Claude Code
Generated with GitHub Copilot`
	result := tasks.DetectAIInText(text)
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "claude_code")
	assert.Contains(t, result.Tools, "copilot")
}

func TestDetectAIInText_DetectsAmazonQ(t *testing.T) {
	result := tasks.DetectAIInText("Generated by Amazon Q")
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "amazon_q")
}

func TestDetectAIInText_DetectsWindsurf(t *testing.T) {
	result := tasks.DetectAIInText("Generated with Windsurf")
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "windsurf")
}

func TestDetectAIInText_DetectsGemini(t *testing.T) {
	result := tasks.DetectAIInText("Gemini Code Assist helped with this")
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "gemini")
}

func TestDetectAIInText_DetectsCodeium(t *testing.T) {
	result := tasks.DetectAIInText("Generated using codeium")
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "windsurf")
}

func TestDetectAIInText_DetectsCodeRabbit(t *testing.T) {
	result := tasks.DetectAIInText("Reviewed by coderabbit")
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "coderabbit")
}

func TestDetectAIInText_DetectsCodeRabbitHyphenated(t *testing.T) {
	result := tasks.DetectAIInText("code-rabbit reviewed this")
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "coderabbit")
}

// Email detection tests
func TestDetectAIInEmail_DetectsCopilotEmail(t *testing.T) {
	result := tasks.DetectAIInEmail("copilot@github.com")
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "copilot")
	assert.GreaterOrEqual(t, result.Confidence, 90)
}

func TestDetectAIInEmail_DetectsAnthropicEmail(t *testing.T) {
	result := tasks.DetectAIInEmail("noreply@anthropic.com")
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "claude_code")
}

func TestDetectAIInEmail_NoDetectionRegularEmail(t *testing.T) {
	result := tasks.DetectAIInEmail("dev@example.com")
	assert.False(t, result.Detected)
}

// Generic AI patterns
func TestDetectAIInText_GenericAIGenerated(t *testing.T) {
	result := tasks.DetectAIInText("This is AI-generated code")
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "unknown")
}

func TestDetectAIInText_GenericAIAssisted(t *testing.T) {
	result := tasks.DetectAIInText("AI-assisted development")
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "unknown")
}

func TestDetectAIInText_GenericGeneratedByAI(t *testing.T) {
	result := tasks.DetectAIInText("This was generated by AI")
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "unknown")
}

func TestDetectAIInText_GenericWrittenByAI(t *testing.T) {
	result := tasks.DetectAIInText("Code written by AI")
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "unknown")
}

func TestDetectAIInText_GenericLLMGenerated(t *testing.T) {
	result := tasks.DetectAIInText("LLM-generated content")
	assert.True(t, result.Detected)
	assert.Contains(t, result.Tools, "unknown")
}

// Combined result tests
func TestCombineResults_PrioritizesSpecificOverUnknown(t *testing.T) {
	r1 := tasks.DetectionResult{
		Detected:   true,
		Tools:      []string{"unknown"},
		Confidence: 60,
	}
	r2 := tasks.DetectionResult{
		Detected:   true,
		Tools:      []string{"claude_code"},
		Confidence: 95,
	}
	combined := tasks.CombineResults(r1, r2)
	assert.Equal(t, "claude_code", combined.Tools[0]) // Specific tool first
	assert.Equal(t, 95, combined.Confidence)
}

func TestCombineResults_ReturnsUnknownWhenOnlyOption(t *testing.T) {
	r1 := tasks.DetectionResult{
		Detected:   true,
		Tools:      []string{"unknown"},
		Confidence: 60,
	}
	combined := tasks.CombineResults(r1)
	assert.Equal(t, "unknown", combined.Tools[0])
}

// No false positives
func TestNoFalsePositives(t *testing.T) {
	normalTexts := []string{
		"Add user authentication feature",
		"Fix bug in login flow",
		"Refactor database queries for performance",
		"Co-Authored-By: John Doe <john@company.com>",
		"Co-Authored-By: Jane Smith <jane@example.org>",
		"Update dependencies",
		"Merge branch 'feature' into main",
		"Initial commit",
		"The code generator module was updated",     // "generator" shouldn't trigger
		"This is a generic solution",                // "generic" shouldn't trigger
		"AI is mentioned but not as a tool marker",  // Just mentioning AI
	}

	for _, text := range normalTexts {
		t.Run(text[:min(30, len(text))], func(t *testing.T) {
			result := tasks.DetectAIInText(text)
			assert.False(t, result.Detected, "Should not detect AI in: %s", text)
		})
	}
}

// All tool trailer patterns
func TestAllToolTrailerPatterns(t *testing.T) {
	testCases := []struct {
		name         string
		text         string
		expectedTool string
	}{
		{"Claude trailer", "Co-Authored-By: Claude <noreply@anthropic.com>", "claude_code"},
		{"Claude Sonnet trailer", "Co-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>", "claude_code"},
		{"Anthropic trailer", "Co-Authored-By: someone@anthropic.com", "claude_code"},
		{"Copilot @mention", "Co-Authored-By: @copilot", "copilot"},
		{"GitHub Copilot", "Co-Authored-By: GitHub Copilot", "copilot"},
		{"Cursor trailer", "Co-Authored-By: Cursor", "cursor"},
		{"Amazon Q trailer", "Co-Authored-By: Amazon Q", "amazon_q"},
		{"Gemini trailer", "Co-Authored-By: Gemini", "gemini"},
		{"Google Code Assist", "Co-Authored-By: Google Code Assist", "gemini"},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			result := tasks.DetectAIInText(tc.text)
			assert.True(t, result.Detected, "Should detect %s in: %s", tc.expectedTool, tc.text)
			assert.Contains(t, result.Tools, tc.expectedTool)
			assert.GreaterOrEqual(t, result.Confidence, 90, "Trailers should have high confidence")
		})
	}
}

// All tool body patterns
func TestAllToolBodyPatterns(t *testing.T) {
	testCases := []struct {
		name         string
		text         string
		expectedTool string
	}{
		{"Claude Code bracket", "[Claude Code]", "claude_code"},
		{"Generated with Claude Code", "Generated with Claude Code", "claude_code"},
		{"Generated by Claude", "Generated by Claude", "claude_code"},
		{"Claude URL", "https://claude.ai/claude-code", "claude_code"},
		{"Cursor bracket", "[Cursor]", "cursor"},
		{"Generated with Cursor", "Generated with Cursor", "cursor"},
		{"cursor.com", "Built using cursor.com", "cursor"},
		{"GitHub Copilot bracket", "[GitHub Copilot]", "copilot"},
		{"Generated with Copilot", "Generated with Copilot", "copilot"},
		{"copilot-generated", "copilot-generated code", "copilot"},
		{"Codex bracket", "[Codex]", "codex"},
		{"Generated with OpenAI Codex", "Generated with OpenAI Codex", "codex"},
		{"Amazon Q bracket", "[Amazon Q]", "amazon_q"},
		{"Generated by Amazon Q", "Generated by Amazon Q", "amazon_q"},
		{"Windsurf bracket", "[Windsurf]", "windsurf"},
		{"Generated with Windsurf", "Generated with Windsurf", "windsurf"},
		{"Codeium", "Using codeium for development", "windsurf"},
		{"Generated with Gemini", "Generated with Gemini", "gemini"},
		{"Gemini Code Assist", "Gemini Code Assist helped", "gemini"},
		{"CodeRabbit", "Reviewed by coderabbit", "coderabbit"},
		{"Code-Rabbit hyphenated", "code-rabbit analysis", "coderabbit"},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			result := tasks.DetectAIInText(tc.text)
			assert.True(t, result.Detected, "Should detect %s in: %s", tc.expectedTool, tc.text)
			assert.Contains(t, result.Tools, tc.expectedTool)
		})
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
