{
 "title": "Engineering Throughput and Cycle Time - Team View",
 "tags": [ "Engineering Leads Dashboard" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "select distinct name from projects"
   },
   {
    "name": "team1",
    "label": "Team1",
    "query": "select concat(name, '--', id) as text from teams"
   },
   {
    "name": "team2",
    "label": "Team2",
    "query": "select concat(name, '--', id) as text from teams"
   },
   {
    "name": "priority",
    "label": "P0+P1 Priority",
    "query": "select distinct priority from issues where priority != ''"
   },
   {
    "name": "interval",
    "label": "Time Interval",
    "query": "Month : DAYOFMONTH, Week : WEEKDAY"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard shows the engineering throughput and and cycle time, which helps to identify productivity and bottlenecks of the development process.\n- Data Source Required: GitHub and Jira([transformation](https://devlake.apache.org/docs/UserManuals/ConfigUI/Jira#step-3---adding-transformation-rules-optional) required to tell DevLake what the story_points field is). You also need to do [team configuration](https://devlake.apache.org/docs/Configuration/TeamConfiguration) to use this dashboard."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "1. Total and Avg PRs Opened/Merged",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total PRs Opened",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    pr.id,\n    pr.url,\n    pr.created_date,\n    pr.merged_date,\n    pr.author_id,\n    u.id as user_id,\n    u.name as user_name,\n    t.id as team_id,\n    t.name as team\n  FROM pull_requests pr\n    join user_accounts ua on pr.author_id = ua.account_id\n    join users u on ua.user_id = u.id\n    join team_users tu on u.id = tu.user_id\n    join teams t on tu.team_id = t.id\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n  WHERE\n    $__timeFilter(pr.created_date)\n    and pm.project_name in (${project})\n)\n\nSELECT\n  DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n  count(distinct case when team_id in (${team1}) then id else null end) as \"Team1: Total PR Opened\",\n  count(distinct case when team_id in (${team2}) then id else null end) as \"Team2: Total PR Opened\"\nFROM _prs\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "PRs Opened per Member",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    pr.id,\n    pr.url,\n    pr.created_date,\n    pr.merged_date,\n    pr.author_id,\n    u.id as user_id,\n    u.name as user_name,\n    t.id as team_id,\n    t.name as team\n  FROM pull_requests pr\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n    join user_accounts ua on pr.author_id = ua.account_id\n    join users u on ua.user_id = u.id\n    join team_users tu on u.id = tu.user_id\n    join teams t on tu.team_id = t.id\n  WHERE\n    $__timeFilter(pr.created_date)\n    and pm.project_name in (${project})\n)\n\nSELECT\n  DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n  count(distinct case when team_id in (${team1}) then id else null end)/(select count(distinct user_id) from team_users where team_id in (${team1})) as \"Team1: PR Opened per Member\",\n  count(distinct case when team_id in (${team2}) then id else null end)/(select count(distinct user_id) from team_users where team_id in (${team2})) as \"Team2: PR Opened per Member\",\n  count(distinct id)/(select count(*) from users) as \"Org: PR Opened per Member\"\nFROM _prs\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Total PRs Merged",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    pr.id,\n    pr.url,\n    pr.created_date,\n    pr.merged_date,\n    pr.author_id,\n    u.id as user_id,\n    u.name as user_name,\n    t.id as team_id,\n    t.name as team\n  FROM pull_requests pr\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n    join user_accounts ua on pr.author_id = ua.account_id\n    join users u on ua.user_id = u.id\n    join team_users tu on u.id = tu.user_id\n    join teams t on tu.team_id = t.id\n  WHERE\n    $__timeFilter(pr.created_date)\n    and pm.project_name in (${project})\n)\n\nSELECT\n  DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n  count(distinct case \n    when team_id in (${team1}) and merged_date is not null then id \n    when team_id in (${team1}) and merged_date is null then null end) as \"Team1: Total PR Merged\",\n  count(distinct case \n    when team_id in (${team2}) and merged_date is not null then id \n    when team_id in (${team2}) and merged_date is null then null end) as \"Team2: Total PR Merged\"\nFROM _prs\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "PRs Merged per Member",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    pr.id,\n    pr.url,\n    pr.created_date,\n    pr.merged_date,\n    pr.author_id,\n    u.id as user_id,\n    u.name as user_name,\n    t.id as team_id,\n    t.name as team\n  FROM pull_requests pr\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n    join user_accounts ua on pr.author_id = ua.account_id\n    join users u on ua.user_id = u.id\n    join team_users tu on u.id = tu.user_id\n    join teams t on tu.team_id = t.id\n  WHERE\n    $__timeFilter(pr.created_date)\n    and pm.project_name in (${project})\n)\n\nSELECT\n  DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n  count(distinct case \n    when team_id in (${team1}) and merged_date is not null then id \n    when team_id in (${team1}) and merged_date is null then null end)/(select count(distinct user_id) from team_users where team_id in (${team1})) as \"Team1: PR Merged per Member\",\n  count(distinct case \n    when team_id in (${team2}) and merged_date is not null then id\n    when team_id in (${team2}) and merged_date is null then null end)/(select count(distinct user_id) from team_users where team_id in (${team2})) as \"Team2: PR Merged per Member\",\n  count(distinct case when merged_date is not null then id end)/(select count(*) from users) as \"Org: PR Merged per Member\"\nFROM _prs\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "2. Issue Completed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Issue Completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "with _issues as(\n  SELECT\n    i.id,\n    i.url,\n    i.created_date,\n    i.status,\n    i.assignee_id,\n    i.story_point,\n    i.priority,\n    u.id as user_id,\n    u.name as user_name,\n    t.id as team_id,\n    t.name as team\n  FROM issues i\n\t  join board_issues bi on i.id = bi.issue_id\n\t  join boards b on bi.board_id = b.id\n\t  join project_mapping pm on b.id = pm.row_id\n  \tjoin user_accounts ua on i.assignee_id = ua.account_id\n    join users u on ua.user_id = u.id\n    join team_users tu on u.id = tu.user_id\n    join teams t on tu.team_id = t.id\n  WHERE\n    $__timeFilter(i.created_date)\n    and pm.project_name in (${project})\n)\n\nSELECT\n  DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n  -- count(i.id) as 'Issues Opened',\n  count(distinct case when status = 'DONE' and team_id in (${team1}) then id else null end) as 'Team1: Issues Completed',\n  count(distinct case when status = 'DONE' and team_id in (${team2}) then id else null end) as 'Team2: Issues Completed'\nFROM _issues\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Issue Completed per Member",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "with _issues as(\n  SELECT\n    distinct i.id,\n    i.url,\n    i.created_date,\n    i.status,\n    i.assignee_id,\n    i.story_point,\n    i.priority,\n    u.id as user_id,\n    u.name as user_name,\n    t.id as team_id,\n    t.name as team\n  FROM issues i\n\t  join board_issues bi on i.id = bi.issue_id\n\t  join boards b on bi.board_id = b.id\n\t  join project_mapping pm on b.id = pm.row_id\n  \tjoin user_accounts ua on i.assignee_id = ua.account_id\n    join users u on ua.user_id = u.id\n    join team_users tu on u.id = tu.user_id\n    join teams t on tu.team_id = t.id\n  WHERE\n    $__timeFilter(i.created_date)\n    and pm.project_name in (${project})\n  ORDER BY 1\n)\n\nSELECT\n  DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n  count(distinct case when status = 'DONE' and team_id in (${team1}) then id else null end)/(select count(distinct user_id) from team_users where team_id in (${team1})) as 'Team1: Issues Completed per Member',\n  count(distinct case when status = 'DONE' and team_id in (${team2}) then id else null end)/(select count(distinct user_id) from team_users where team_id in (${team2})) as 'Team2: Issues Completed per Member',\n  count(distinct id)/(select count(*) from users) as \"Org: Issues Completed per Member\"\nFROM _issues\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "3. Story Points Completed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Story Points Completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "with _issues as(\n  SELECT\n    distinct i.id,\n    i.url,\n    i.created_date,\n    i.status,\n    i.assignee_id,\n    i.story_point,\n    i.priority,\n    u.id as user_id,\n    u.name as user_name,\n    t.id as team_id,\n    t.name as team\n  FROM issues i\n\t  join board_issues bi on i.id = bi.issue_id\n\t  join boards b on bi.board_id = b.id\n\t  join project_mapping pm on b.id = pm.row_id\n  \tjoin user_accounts ua on i.assignee_id = ua.account_id\n    join users u on ua.user_id = u.id\n    join team_users tu on u.id = tu.user_id\n    join teams t on tu.team_id = t.id\n  WHERE\n    $__timeFilter(i.created_date)\n    and pm.project_name in (${project})\n  ORDER BY 1\n)\n\nSELECT\n  DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n  -- count(i.id) as 'Issues Opened',\n  sum(case when status = 'DONE' and team_id in (${team1}) then story_point else 0 end) as 'Team1: Story Points Completed',\n  sum(case when status = 'DONE' and team_id in (${team2}) then story_point else 0 end) as 'Team2: Story Points Completed'\nFROM _issues\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Story Points Completed per Member",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "with _issues as(\n  SELECT\n    distinct i.id,\n    i.url,\n    i.created_date,\n    i.status,\n    i.assignee_id,\n    i.story_point,\n    i.priority,\n    u.id as user_id,\n    u.name as user_name,\n    t.id as team_id,\n    t.name as team\n  FROM issues i\n\t  join board_issues bi on i.id = bi.issue_id\n\t  join boards b on bi.board_id = b.id\n\t  join project_mapping pm on b.id = pm.row_id\n  \tjoin user_accounts ua on i.assignee_id = ua.account_id\n    join users u on ua.user_id = u.id\n    join team_users tu on u.id = tu.user_id\n    join teams t on tu.team_id = t.id\n  WHERE\n    $__timeFilter(i.created_date)\n    and pm.project_name in (${project})\n  ORDER BY 1\n)\n\nSELECT\n  DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n  sum(case when status = 'DONE' and team_id in (${team1}) then story_point else 0 end)/(select count(distinct user_id) from team_users where team_id in (${team1})) as 'Team1: Story Points Completed per Member',\n  sum(case when status = 'DONE' and team_id in (${team2}) then story_point else 0 end)/(select count(distinct user_id) from team_users where team_id in (${team2})) as 'Team2: Story Points Completed per Member',\n  count(distinct id)/(select count(*) FROM users) as \"Org: Story Points Completed per Member\"\nFROM _issues\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "4. PR Review Depth and PR Merged Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": " Average PR Review Depth per Team",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "with _merged_prs as(\n  SELECT\n    distinct pr.id,\n    pr.url,\n    pr.created_date,\n    pr.merged_date,\n    pr.author_id,\n    prc.id as comment_id,\n    u.id as user_id,\n    u.name as user_name,\n    t.id as team_id,\n    t.name as team\n  FROM pull_requests pr\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n    left join pull_request_comments prc on pr.id = prc.pull_request_id\n    join user_accounts ua on pr.author_id = ua.account_id\n    join users u on ua.user_id = u.id\n    join team_users tu on u.id = tu.user_id\n    join teams t on tu.team_id = t.id\n  WHERE\n    $__timeFilter(pr.created_date)\n    and pm.project_name in (${project})\n    and pr.merged_date is not null\n  ORDER BY 1\n)\n\nselect\n  DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n  count(distinct case when team_id in (${team1}) then comment_id else null end)/(select count(distinct user_id) from team_users where team_id in (${team1})) as \"Team1: PR Review Depth\",\n  count(distinct case when team_id in (${team2}) then comment_id else null end)/(select count(distinct user_id) from team_users where team_id in (${team2})) as \"Team2: PR Review Depth\",\n  count(distinct comment_id)/(select count(*) FROM users) as \"Org: PR Review Depth\"\nFROM _merged_prs\nGROUP BY 1"
    }
   ]
  },
  {
   "title": " Average PR Merged Size by Team",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    distinct pr.id,\n    pr.url,\n    pr.created_date,\n    pr.merged_date,\n    pr.author_id,\n    pr.merge_commit_sha,\n    c.additions + c.deletions as loc,\n    u.id as user_id,\n    u.name as user_name,\n    t.id as team_id,\n    t.name as team\n  FROM pull_requests pr\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n   left join commits c on pr.merge_commit_sha = c.sha\n    join user_accounts ua on pr.author_id = ua.account_id\n    join users u on ua.user_id = u.id\n    join team_users tu on u.id = tu.user_id\n    join teams t on tu.team_id = t.id\n  WHERE\n    $__timeFilter(pr.created_date)\n    and pm.project_name in (${project})\n    and pr.status = 'MERGED'\n  ORDER BY 1\n)\n\nselect\n  DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n  sum(case when team_id in (${team1}) then loc else null end)/(select count(distinct user_id) from team_users where team_id in (${team1})) as \"Team1: PR Size\",\n  sum(case when team_id in (${team2}) then loc else null end)/(select count(distinct user_id) from team_users where team_id in (${team2})) as \"Team2: PR Size\",\n  sum(loc)/(select count(*) FROM users) as \"Org: PR Merged Size\"\nFROM _prs\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "5. P0/P1 Bugs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total P0/P1 Bugs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "with _bugs as(\n  SELECT\n    distinct i.id,\n    i.url,\n    i.created_date,\n    i.status,\n    i.assignee_id,\n    i.story_point,\n    i.priority,\n    u.id as user_id,\n    u.name as user_name,\n    t.id as team_id,\n    t.name as team\n  FROM issues i\n\t  join board_issues bi on i.id = bi.issue_id\n\t  join boards b on bi.board_id = b.id\n\t  join project_mapping pm on b.id = pm.row_id\n  \tjoin user_accounts ua on i.assignee_id = ua.account_id\n    join users u on ua.user_id = u.id\n    join team_users tu on u.id = tu.user_id\n    join teams t on tu.team_id = t.id\n  WHERE\n    $__timeFilter(i.created_date)\n    and pm.project_name in (${project})\n    and i.type = 'BUG'\n  ORDER BY 1\n)\n\nSELECT\n  DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n  count(case when team_id in (${team1}) then id else null end) as 'Team1: P0/P1 Bugs',\n  count(case when team_id in (${team2}) then id else null end) as 'Team2: P0/P1 Bugs'\nFROM _bugs\nWHERE\n  -- please choose the priorities in the filter above\n  priority in (${priority})\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "P0/P1 Bugs per Member",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "rawSql": "with _bugs as(\n  SELECT\n    distinct i.id,\n    i.url,\n    i.created_date,\n    i.status,\n    i.assignee_id,\n    i.story_point,\n    i.priority,\n    u.id as user_id,\n    u.name as user_name,\n    t.id as team_id,\n    t.name as team\n  FROM issues i\n\t  join board_issues bi on i.id = bi.issue_id\n\t  join boards b on bi.board_id = b.id\n\t  join project_mapping pm on b.id = pm.row_id\n  \tjoin user_accounts ua on i.assignee_id = ua.account_id\n    join users u on ua.user_id = u.id\n    join team_users tu on u.id = tu.user_id\n    join teams t on tu.team_id = t.id\n  WHERE\n    $__timeFilter(i.created_date)\n    and pm.project_name in (${project})\n    and i.type = 'BUG'\n  ORDER BY 1\n)\n\nSELECT\n  DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n  count(case when team_id in (${team1}) then id else null end)/(select count(distinct user_id) from team_users where team_id in (${team1})) as 'Team1: P0/P1 Bugs per Member',\n  count(case when team_id in (${team2}) then id else null end)/(select count(distinct user_id) from team_users where team_id in (${team2})) as 'Team2: P0/P1 Bugs per Member',\n  count(distinct id)/(select count(*) FROM users) as \"Org: P0/P1 Bugs per Member\"\nFROM _bugs\nWHERE\n  -- please choose the priorities in the filter above\n  priority in (${priority})\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "6. Cycle Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Cycle Time(h)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    pr.id,\n    pr.merged_date as pr_merged_date,\n    -- convert milliseconds to hours (ms / 3600000)\n\t\tcoalesce(prm.pr_cycle_time/3600000,0) as cycle_time,\n\t\tpr.author_id,\n    u.id as user_id,\n    u.name as user_name,\n    t.id as team_id,\n    t.name as team\n  FROM pull_requests pr\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n\t\tleft join project_pr_metrics prm on pr.id = prm.id\n    left join user_accounts ua on pr.author_id = ua.account_id\n    left join users u on ua.user_id = u.id\n    left join team_users tu on u.id = tu.user_id\n    left join teams t on tu.team_id = t.id\n  WHERE\n    $__timeFilter(pr.merged_date)\n    and pm.project_name in (${project})\n  GROUP BY 1,2,3,4,5,6,7,8\n)\n\nSELECT \n  DATE_ADD(date(pr_merged_date), INTERVAL -$interval(date(pr_merged_date))+1 DAY) as time,\n  avg(case when team_id in (${team1}) then cycle_time end) as 'Team1: Avg Cycle Time(h)',\n  avg(case when team_id in (${team2}) then cycle_time end) as 'Team2: Avg Cycle Time(h)'\nFROM _prs\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PR Coding Time(h)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 58 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    pr.id,\n    pr.merged_date as pr_merged_date,\n    -- convert milliseconds to hours (ms / 3600000)\n\t\tcoalesce(prm.pr_coding_time/3600000,0) as coding_time,\n\t\tpr.author_id,\n    u.id as user_id,\n    u.name as user_name,\n    t.id as team_id,\n    t.name as team\n  FROM pull_requests pr\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n\t\tleft join project_pr_metrics prm on pr.id = prm.id\n    left join user_accounts ua on pr.author_id = ua.account_id\n    left join users u on ua.user_id = u.id\n    left join team_users tu on u.id = tu.user_id\n    left join teams t on tu.team_id = t.id\n  WHERE\n    $__timeFilter(pr.merged_date)\n    and pm.project_name in (${project})\n  GROUP BY 1,2,3,4,5,6,7,8\n)\n\nSELECT \n  DATE_ADD(date(pr_merged_date), INTERVAL -$interval(date(pr_merged_date))+1 DAY) as time,\n  avg(case when team_id in (${team1}) then coding_time end) as 'Team1: Avg Coding Time(h)',\n  avg(case when team_id in (${team2}) then coding_time end) as 'Team2: Avg Coding Time(h)'\nFROM _prs\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PR Pickup Time(h)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 58 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    pr.id,\n    pr.merged_date as pr_merged_date,\n    -- convert milliseconds to hours (ms / 3600000)\n\t\tcoalesce(prm.pr_pickup_time/3600000,0) as pickup_time,\n\t\tpr.author_id,\n    u.id as user_id,\n    u.name as user_name,\n    t.id as team_id,\n    t.name as team\n  FROM pull_requests pr\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n\t\tleft join project_pr_metrics prm on pr.id = prm.id\n    left join user_accounts ua on pr.author_id = ua.account_id\n    left join users u on ua.user_id = u.id\n    left join team_users tu on u.id = tu.user_id\n    left join teams t on tu.team_id = t.id\n  WHERE\n    $__timeFilter(pr.merged_date)\n    and pm.project_name in (${project})\n  GROUP BY 1,2,3,4,5,6,7,8\n)\n\nSELECT \n  DATE_ADD(date(pr_merged_date), INTERVAL -$interval(date(pr_merged_date))+1 DAY) as time,\n  avg(case when team_id in (${team1}) then pickup_time end) as 'Team1: Avg Pickup Time(h)',\n  avg(case when team_id in (${team2}) then pickup_time end) as 'Team2: Avg Pickup Time(h)'\nFROM _prs\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PR Review Time(h)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 58 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    pr.id,\n    pr.merged_date as pr_merged_date,\n    -- convert milliseconds to hours (ms / 3600000)\n\t\tcoalesce(prm.pr_review_time/3600000,0) as review_time,\n\t\tpr.author_id,\n    u.id as user_id,\n    u.name as user_name,\n    t.id as team_id,\n    t.name as team\n  FROM pull_requests pr\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n\t\tleft join project_pr_metrics prm on pr.id = prm.id\n    left join user_accounts ua on pr.author_id = ua.account_id\n    left join users u on ua.user_id = u.id\n    left join team_users tu on u.id = tu.user_id\n    left join teams t on tu.team_id = t.id\n  WHERE\n    $__timeFilter(pr.merged_date)\n    and pm.project_name in (${project})\n  GROUP BY 1,2,3,4,5,6,7,8\n)\n\nSELECT \n  DATE_ADD(date(pr_merged_date), INTERVAL -$interval(date(pr_merged_date))+1 DAY) as time,\n  avg(case when team_id in (${team1}) then review_time end) as 'Team1: Avg Review Time(h)',\n  avg(case when team_id in (${team2}) then review_time end) as 'Team2: Avg Review Time(h)'\nFROM _prs\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "PR Deploy Time(h)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 58 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    pr.id,\n    pr.merged_date as pr_merged_date,\n    -- convert milliseconds to hours (ms / 3600000)\n\t\tcoalesce(prm.pr_deploy_time/3600000,0) as deploy_time,\n\t\tpr.author_id,\n    u.id as user_id,\n    u.name as user_name,\n    t.id as team_id,\n    t.name as team\n  FROM pull_requests pr\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n\t\tleft join project_pr_metrics prm on pr.id = prm.id\n    left join user_accounts ua on pr.author_id = ua.account_id\n    left join users u on ua.user_id = u.id\n    left join team_users tu on u.id = tu.user_id\n    left join teams t on tu.team_id = t.id\n  WHERE\n    $__timeFilter(pr.merged_date)\n    and pm.project_name in (${project})\n  GROUP BY 1,2,3,4,5,6,7,8\n)\n\nSELECT \n  DATE_ADD(date(pr_merged_date), INTERVAL -$interval(date(pr_merged_date))+1 DAY) as time,\n  avg(case when team_id in (${team1}) then deploy_time end) as 'Team1: Avg Deploy Time(h)',\n  avg(case when team_id in (${team2}) then deploy_time end) as 'Team2: Avg Deploy Time(h)'\nFROM _prs\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "7. PRs Merged w/o Review",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PRs Merged w/o Review",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "rawSql": "with _merged_prs as(\n  SELECT\n    distinct pr.id,\n    pr.url,\n    pr.created_date,\n    pr.merged_date,\n    pr.author_id,\n    u.id as user_id,\n    u.name as user_name,\n    t.id as team_id,\n    t.name as team\n  FROM pull_requests pr\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n    join user_accounts ua on pr.author_id = ua.account_id\n    join users u on ua.user_id = u.id\n    join team_users tu on u.id = tu.user_id\n    join teams t on tu.team_id = t.id\n  WHERE\n    $__timeFilter(pr.created_date)\n    and pm.project_name in (${project})\n    and pr.merged_date is not null\n  ORDER BY 1\n)\n\nSELECT\n  DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n  count(distinct case when team_id in (${team1}) and id not in (SELECT pull_request_id FROM pull_request_comments) then id else null end) as \"Team1: PRs Merged w/o Review\",\n  count(distinct case when team_id in (${team2}) and id not in (SELECT pull_request_id FROM pull_request_comments) then id else null end) as \"Team2: PRs Merged w/o Review\"\nFROM _merged_prs\nGROUP BY 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 73 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide)."
   },
   "targets": [
    {}
   ]
  }
 ]
}