/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package tasks

import (
	"regexp"
	"strings"
	"time"

	"github.com/apache/incubator-devlake/core/dal"
	"github.com/apache/incubator-devlake/core/errors"
	"github.com/apache/incubator-devlake/core/models/domainlayer/code"
	"github.com/apache/incubator-devlake/core/plugin"
	"github.com/apache/incubator-devlake/plugins/aidetector/models"
)

var DetectExplicitSignalsMeta = plugin.SubTaskMeta{
	Name:             "detectExplicitSignals",
	EntryPoint:       DetectExplicitSignals,
	EnabledByDefault: true,
	Description:      "Detect explicit AI tool markers in git trailers, PR bodies, and commit messages",
	DomainTypes:      []string{plugin.DOMAIN_TYPE_CODE},
}

// Default confidence levels (can be overridden via settings)
// These are used when settings are not yet loaded or as fallbacks
const (
	DefaultConfidenceTrailer = 95 // Git trailers - highest confidence
	DefaultConfidenceBody    = 85 // PR body/commit markers - high confidence
	DefaultConfidenceGeneric = 60 // Generic AI indicators - lower confidence
	DefaultConfidenceEmail   = 90 // Known AI bot emails
)

// AIToolPattern defines patterns for detecting a specific AI tool
type AIToolPattern struct {
	Tool       string
	Confidence int
	Patterns   []*regexp.Regexp
}

// Git trailer patterns - highest confidence (0.95)
// These are explicit markers left by AI tools in commit trailers
var trailerPatterns = []AIToolPattern{
	{
		Tool:       "claude_code",
		Confidence: DefaultConfidenceTrailer,
		Patterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)Co-Authored-By:\s*Claude`),
			regexp.MustCompile(`(?i)Co-Authored-By:.*claude.*sonnet`),
			regexp.MustCompile(`(?i)Co-Authored-By:.*anthropic`),
		},
	},
	{
		Tool:       "copilot",
		Confidence: DefaultConfidenceTrailer,
		Patterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)Co-Authored-By:\s*@copilot`),
			regexp.MustCompile(`(?i)Co-Authored-By:.*github.*copilot`),
		},
	},
	{
		Tool:       "cursor",
		Confidence: DefaultConfidenceTrailer,
		Patterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)Co-Authored-By:\s*Cursor`),
		},
	},
	{
		Tool:       "amazon_q",
		Confidence: DefaultConfidenceTrailer,
		Patterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)Co-Authored-By:.*Amazon\s*Q`),
		},
	},
	{
		Tool:       "gemini",
		Confidence: DefaultConfidenceTrailer,
		Patterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)Co-Authored-By:.*Gemini`),
			regexp.MustCompile(`(?i)Co-Authored-By:.*Google.*Code\s*Assist`),
		},
	},
}

// PR body / commit message markers - high confidence (0.85)
var bodyPatterns = []AIToolPattern{
	{
		Tool:       "claude_code",
		Confidence: DefaultConfidenceBody,
		Patterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)Generated with \[?Claude Code\]?`),
			regexp.MustCompile(`(?i)Generated by Claude`),
			regexp.MustCompile(`(?i)\[Claude Code\]`),
			regexp.MustCompile(`(?i)claude\.ai/claude-code`),
		},
	},
	{
		Tool:       "cursor",
		Confidence: DefaultConfidenceBody,
		Patterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)Generated (?:with|by) Cursor`),
			regexp.MustCompile(`(?i)\[Cursor\]`),
			regexp.MustCompile(`(?i)cursor\.com`),
		},
	},
	{
		Tool:       "copilot",
		Confidence: DefaultConfidenceBody,
		Patterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)Generated (?:with|by) (?:GitHub )?Copilot`),
			regexp.MustCompile(`(?i)\[GitHub Copilot\]`),
			regexp.MustCompile(`(?i)copilot-generated`),
		},
	},
	{
		Tool:       "codex",
		Confidence: DefaultConfidenceBody,
		Patterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)Generated (?:with|by) (?:OpenAI )?Codex`),
			regexp.MustCompile(`(?i)\[Codex\]`),
		},
	},
	{
		Tool:       "amazon_q",
		Confidence: DefaultConfidenceBody,
		Patterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)Generated (?:with|by) Amazon Q`),
			regexp.MustCompile(`(?i)\[Amazon Q\]`),
		},
	},
	{
		Tool:       "windsurf",
		Confidence: DefaultConfidenceBody,
		Patterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)Generated (?:with|by) Windsurf`),
			regexp.MustCompile(`(?i)\[Windsurf\]`),
			regexp.MustCompile(`(?i)codeium`),
		},
	},
	{
		Tool:       "gemini",
		Confidence: DefaultConfidenceBody,
		Patterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)Generated (?:with|by) Gemini`),
			regexp.MustCompile(`(?i)Gemini Code Assist`),
		},
	},
	{
		Tool:       "coderabbit",
		Confidence: DefaultConfidenceBody,
		Patterns: []*regexp.Regexp{
			regexp.MustCompile(`(?i)coderabbit`),
			regexp.MustCompile(`(?i)code-rabbit`),
		},
	},
}

// Generic AI indicators - lower confidence (0.6)
// Tool is unknown but we know AI was involved
var genericAIPatterns = []*regexp.Regexp{
	regexp.MustCompile(`(?i)AI-generated`),
	regexp.MustCompile(`(?i)AI-assisted`),
	regexp.MustCompile(`(?i)generated by AI`),
	regexp.MustCompile(`(?i)written by AI`),
	regexp.MustCompile(`(?i)LLM-generated`),
}

// Known AI bot email patterns
var aiEmailPatterns = map[string]string{
	"copilot":               "copilot",
	"github-copilot":        "copilot",
	"noreply@anthropic.com": "claude_code",
}

// DetectionResult holds the result of AI detection for a single text
type DetectionResult struct {
	Detected   bool
	Tools      []string
	Confidence int
	Signals    []string
}

func DetectExplicitSignals(taskCtx plugin.SubTaskContext) errors.Error {
	db := taskCtx.GetDal()
	data := taskCtx.GetData().(*AIDetectorTaskData)
	logger := taskCtx.GetLogger()

	logger.Info("Starting detectExplicitSignals for project: %s", data.Options.ProjectName)

	// Get all PRs for this project
	var prs []code.PullRequest
	clauses := []dal.Clause{
		dal.From(&code.PullRequest{}),
		dal.Join("LEFT JOIN project_mapping pm ON pm.table = 'repos' AND pm.row_id = pull_requests.base_repo_id"),
		dal.Where("pm.project_name = ?", data.Options.ProjectName),
	}

	err := db.All(&prs, clauses...)
	if err != nil {
		return errors.Default.Wrap(err, "failed to query pull requests")
	}

	logger.Info("Scanning %d PRs for explicit AI tool markers", len(prs))

	explicitDetectionCount := 0
	for _, pr := range prs {
		// Get or create signal for this PR
		var signal models.AIUsageSignal
		err := db.First(&signal, dal.Where("pull_request_id = ?", pr.Id))
		if err != nil {
			// Signal doesn't exist yet, create minimal one
			signal = models.AIUsageSignal{
				Id:            pr.Id,
				PullRequestId: pr.Id,
				DetectedAt:    resolveSignalDetectedAt(&pr),
				CreatedAt:     time.Now(),
			}
		}
		// Keep detected_at anchored to PR event time, not batch run time.
		signal.DetectedAt = resolveSignalDetectedAt(&pr)

		// Analyze PR title
		titleResult := DetectAIInText(pr.Title)

		// Analyze PR description/body
		bodyResult := DetectAIInText(pr.Description)

		// Get commits for this PR and analyze messages
		var commits []code.Commit
		commitClauses := []dal.Clause{
			dal.From(&code.Commit{}),
			dal.Join("LEFT JOIN pull_request_commits prc ON prc.commit_sha = commits.sha"),
			dal.Where("prc.pull_request_id = ?", pr.Id),
		}

		var commitResults []DetectionResult
		if err := db.All(&commits, commitClauses...); err != nil {
			logger.Error(err, "failed to get commits for PR %s", pr.Id)
		} else {
			for _, commit := range commits {
				// Check commit message
				msgResult := DetectAIInText(commit.Message)
				if msgResult.Detected {
					commitResults = append(commitResults, msgResult)
				}

				// Check author email for known AI bot patterns
				emailResult := DetectAIInEmail(commit.AuthorEmail)
				if emailResult.Detected {
					commitResults = append(commitResults, emailResult)
				}
			}
		}

		// Combine all results
		allResults := []DetectionResult{titleResult, bodyResult}
		allResults = append(allResults, commitResults...)
		combined := CombineResults(allResults...)

		if combined.Detected {
			explicitDetectionCount++

			// Set explicit detection fields
			signal.ExplicitToolDetected = true
			signal.ExplicitTools = strings.Join(combined.Tools, ",")
			signal.ExplicitPatterns = strings.Join(combined.Signals, "; ")

			// Use the highest confidence as the score (scaled to 0-70 for the 100-point system)
			// Explicit tool detection is highly reliable and should carry significant weight
			// We give it up to 70 points (out of 100 total) to ensure proper AI detection
			// For confidence of 85-95, this gives 68-76 points (capped at 70)
			signal.ExplicitSignalScore = min(int(float64(combined.Confidence)*0.8), 70)

			// Set detected tool to the first (primary) tool
			if len(combined.Tools) > 0 {
				signal.DetectedTool = combined.Tools[0]
			}

			logger.Info("PR %s: Explicit AI tool detected: %v (confidence: %d)", pr.Id, combined.Tools, combined.Confidence)
		}

		// Save the updated signal
		if err := db.CreateOrUpdate(&signal); err != nil {
			logger.Error(err, "failed to save signal for PR %s", pr.Id)
		}
	}

	logger.Info("Completed detectExplicitSignals: %d/%d PRs have explicit AI markers",
		explicitDetectionCount, len(prs))

	return nil
}

// DetectAIInText analyzes text for AI tool markers
// This matches the detect_ai_in_text function from eng-product-metrics
func DetectAIInText(text string) DetectionResult {
	if text == "" {
		return DetectionResult{Detected: false}
	}

	var detectedTools []string
	var signals []string
	maxConfidence := 0

	// Check git trailers - highest confidence
	for _, tp := range trailerPatterns {
		for _, pattern := range tp.Patterns {
			if pattern.MatchString(text) {
				if !contains(detectedTools, tp.Tool) {
					detectedTools = append(detectedTools, tp.Tool)
				}
				signals = append(signals, "trailer:"+pattern.String())
				if tp.Confidence > maxConfidence {
					maxConfidence = tp.Confidence
				}
				break // Only match first pattern per tool
			}
		}
	}

	// Check body markers - high confidence
	for _, bp := range bodyPatterns {
		for _, pattern := range bp.Patterns {
			if pattern.MatchString(text) {
				if !contains(detectedTools, bp.Tool) {
					detectedTools = append(detectedTools, bp.Tool)
				}
				signals = append(signals, "body:"+pattern.String())
				if bp.Confidence > maxConfidence {
					maxConfidence = bp.Confidence
				}
				break
			}
		}
	}

	// Check generic AI indicators - lower confidence
	for _, pattern := range genericAIPatterns {
		if pattern.MatchString(text) {
			if !contains(detectedTools, "unknown") {
				detectedTools = append(detectedTools, "unknown")
			}
			signals = append(signals, "generic:"+pattern.String())
			if DefaultConfidenceGeneric > maxConfidence {
				maxConfidence = DefaultConfidenceGeneric
			}
		}
	}

	return DetectionResult{
		Detected:   len(detectedTools) > 0,
		Tools:      detectedTools,
		Confidence: maxConfidence,
		Signals:    signals,
	}
}

// DetectAIInEmail checks if an email belongs to a known AI bot
func DetectAIInEmail(email string) DetectionResult {
	if email == "" {
		return DetectionResult{Detected: false}
	}

	emailLower := strings.ToLower(email)
	for pattern, tool := range aiEmailPatterns {
		if strings.Contains(emailLower, pattern) {
			return DetectionResult{
				Detected:   true,
				Tools:      []string{tool},
				Confidence: DefaultConfidenceEmail,
				Signals:    []string{"email:" + email},
			}
		}
	}

	return DetectionResult{Detected: false}
}

// CombineResults merges multiple detection results
func CombineResults(results ...DetectionResult) DetectionResult {
	var allTools []string
	var allSignals []string
	maxConfidence := 0

	for _, r := range results {
		if r.Detected {
			for _, tool := range r.Tools {
				if !contains(allTools, tool) {
					allTools = append(allTools, tool)
				}
			}
			allSignals = append(allSignals, r.Signals...)
			if r.Confidence > maxConfidence {
				maxConfidence = r.Confidence
			}
		}
	}

	// Also accept slice of results
	return DetectionResult{
		Detected:   len(allTools) > 0,
		Tools:      prioritizeTools(allTools),
		Confidence: maxConfidence,
		Signals:    allSignals,
	}
}

// prioritizeTools puts specific tools before "unknown"
func prioritizeTools(tools []string) []string {
	var specific []string
	hasUnknown := false

	for _, t := range tools {
		if t == "unknown" {
			hasUnknown = true
		} else {
			specific = append(specific, t)
		}
	}

	if hasUnknown && len(specific) == 0 {
		return []string{"unknown"}
	}
	return specific
}

// UniqueStrings removes duplicates from a string slice
// Exported for testing
func UniqueStrings(input []string) []string {
	seen := make(map[string]bool)
	result := []string{}
	for _, s := range input {
		if !seen[s] {
			seen[s] = true
			result = append(result, s)
		}
	}
	return result
}

// contains checks if a string slice contains a value
func contains(slice []string, val string) bool {
	for _, s := range slice {
		if s == val {
			return true
		}
	}
	return false
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
