{
 "title": "Weekly Bug Retro",
 "tags": [
  "Engineering Leads Dashboard",
  "Highlights"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "board_id",
    "label": "Board",
    "query": "SELECT name || '-' || id AS text FROM boards"
   },
   {
    "name": "issue_type",
    "label": "Issue Type",
    "query": "SELECT DISTINCT type FROM issues"
   },
   {
    "name": "priority",
    "label": "Priority",
    "query": "SELECT DISTINCT priority FROM issues"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard can be used to track bugs with metrics such as [Bug Age](https://devlake.apache.org/docs/Metrics/BugAge).\n- Data Source Required: One of the issue tracking tools, e.g. [GitHub](https://devlake.apache.org/docs/UserManuals/ConfigUI/GitHub#step-3---adding-transformation-rules-optional), [GitLab](https://devlake.apache.org/docs/Configuration/GitLab) or [Jira](https://devlake.apache.org/docs/UserManuals/ConfigUI/Jira#step-3---adding-transformation-rules-optional) (Scope Config required to define which issues are bugs)."
   },
   "targets": [
    {}
   ]
  },
  { "title": "Overall Bug Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Weekly New Bugs [Selected Time Range]",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "WITH bugs AS (SELECT CAST(i.created_date AS DATE) + -(EXTRACT(ISODOW FROM CAST(i.created_date AS DATE)) - 1) * INTERVAL '1 day' AS time, COUNT(DISTINCT i.id) AS bug_count FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND i.status <> 'REJECTED' AND $__timeFilter(i.created_date) AND ('${board_id:csv}' = '' OR b.id::text = ANY(ARRAY[${board_id:singlequote}]::text[])) GROUP BY \"time\" ORDER BY time DESC NULLS LAST), calendar_date AS (SELECT CAST(($__timeTo()::timestamp - INTERVAL '1 day') AS DATE) AS d FROM (SELECT 0 AS \"H\" UNION ALL SELECT 100 UNION ALL SELECT 200 UNION ALL SELECT 300) AS \"H\" CROSS JOIN (SELECT 0 AS \"T\" UNION ALL SELECT 10 UNION ALL SELECT 20 UNION ALL SELECT 30 UNION ALL SELECT 40 UNION ALL SELECT 50 UNION ALL SELECT 60 UNION ALL SELECT 70 UNION ALL SELECT 80 UNION ALL SELECT 90) AS \"T\" CROSS JOIN (SELECT 0 AS \"U\" UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS \"U\" WHERE ($__timeTo()::timestamp - INTERVAL '1 day') >= ($__timeTo()::timestamp - INTERVAL '6 MONTH')), calendar_weeks AS (SELECT DISTINCT CAST(CAST(d AS DATE) + -(EXTRACT(ISODOW FROM CAST(d AS DATE)) - 1) * INTERVAL '1 day' AS DATE) AS start_of_week FROM calendar_date ORDER BY 1 ASC NULLS FIRST) SELECT TO_CHAR(CAST(cw.start_of_week AS TIMESTAMP), 'MM/DD') || ' - ' || TO_CHAR(CAST(cw.start_of_week + INTERVAL '7 DAY' AS TIMESTAMP), 'MM/DD') AS week, CASE WHEN NOT bug_count IS NULL THEN bug_count ELSE 0 END AS \"Weekly New Bugs\" FROM calendar_weeks AS cw LEFT JOIN bugs AS b ON cw.start_of_week = b.time ORDER BY cw.start_of_week ASC NULLS FIRST"
    }
   ]
  },
  {
   "title": "Weekly Closed Bugs [Selected Time Range]",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "WITH bugs AS (SELECT CAST(i.resolution_date AS DATE) + -(EXTRACT(ISODOW FROM CAST(i.resolution_date AS DATE)) - 1) * INTERVAL '1 day' AS time, COUNT(DISTINCT i.id) AS bug_count FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND status = 'DONE' AND i.status <> 'REJECTED' AND $__timeFilter(i.resolution_date) AND ('${board_id:csv}' = '' OR b.id::text = ANY(ARRAY[${board_id:singlequote}]::text[])) GROUP BY \"time\" ORDER BY time DESC NULLS LAST), calendar_date AS (SELECT CAST(($__timeTo()::timestamp - INTERVAL '1 day') AS DATE) AS d FROM (SELECT 0 AS \"H\" UNION ALL SELECT 100 UNION ALL SELECT 200 UNION ALL SELECT 300) AS \"H\" CROSS JOIN (SELECT 0 AS \"T\" UNION ALL SELECT 10 UNION ALL SELECT 20 UNION ALL SELECT 30 UNION ALL SELECT 40 UNION ALL SELECT 50 UNION ALL SELECT 60 UNION ALL SELECT 70 UNION ALL SELECT 80 UNION ALL SELECT 90) AS \"T\" CROSS JOIN (SELECT 0 AS \"U\" UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS \"U\" WHERE ($__timeTo()::timestamp - INTERVAL '1 day') >= ($__timeTo()::timestamp - INTERVAL '6 MONTH')), calendar_weeks AS (SELECT DISTINCT CAST(CAST(d AS DATE) + -(EXTRACT(ISODOW FROM CAST(d AS DATE)) - 1) * INTERVAL '1 day' AS DATE) AS start_of_week FROM calendar_date ORDER BY 1 ASC NULLS FIRST) SELECT TO_CHAR(CAST(cw.start_of_week AS TIMESTAMP), 'MM/DD') || ' - ' || TO_CHAR(CAST(cw.start_of_week + INTERVAL '7 DAY' AS TIMESTAMP), 'MM/DD') AS week, CASE WHEN NOT bug_count IS NULL THEN bug_count ELSE 0 END AS \"Weekly Closed Bugs\" FROM calendar_weeks AS cw LEFT JOIN bugs AS b ON cw.start_of_week = b.time ORDER BY cw.start_of_week ASC NULLS FIRST"
    }
   ]
  },
  {
   "title": "Total Outstanding Bug Count by Week [Selected Time Range]",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "WITH calendar_date AS (SELECT CAST(($__timeTo()::timestamp - INTERVAL '1 day') AS DATE) AS d FROM (SELECT 0 AS \"H\" UNION ALL SELECT 100 UNION ALL SELECT 200 UNION ALL SELECT 300) AS \"H\" CROSS JOIN (SELECT 0 AS \"T\" UNION ALL SELECT 10 UNION ALL SELECT 20 UNION ALL SELECT 30 UNION ALL SELECT 40 UNION ALL SELECT 50 UNION ALL SELECT 60 UNION ALL SELECT 70 UNION ALL SELECT 80 UNION ALL SELECT 90) AS \"T\" CROSS JOIN (SELECT 0 AS \"U\" UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) AS \"U\" WHERE ($__timeTo()::timestamp - INTERVAL '1 day') >= ($__timeTo()::timestamp - INTERVAL '6 MONTH')), calendar_weeks AS (SELECT DISTINCT CAST(CAST(d AS DATE) + -(EXTRACT(ISODOW FROM CAST(d AS DATE)) - 1) * INTERVAL '1 day' AS DATE) AS start_of_week FROM calendar_date ORDER BY 1 ASC NULLS FIRST), created_bugs AS (SELECT CAST(i.created_date AS DATE) + -(EXTRACT(ISODOW FROM CAST(i.created_date AS DATE)) - 1) * INTERVAL '1 day' AS time, COUNT(DISTINCT i.id) AS bug_count FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND i.status <> 'REJECTED' AND $__timeFilter(i.created_date) AND ('${board_id:csv}' = '' OR b.id::text = ANY(ARRAY[${board_id:singlequote}]::text[])) GROUP BY \"time\" ORDER BY time DESC NULLS LAST), resolved_bugs AS (SELECT CAST(i.resolution_date AS DATE) + -(EXTRACT(ISODOW FROM CAST(i.resolution_date AS DATE)) - 1) * INTERVAL '1 day' AS time, COUNT(DISTINCT i.id) AS bug_count FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND status = 'DONE' AND i.status <> 'REJECTED' AND $__timeFilter(i.resolution_date) AND ('${board_id:csv}' = '' OR b.id::text = ANY(ARRAY[${board_id:singlequote}]::text[])) GROUP BY \"time\" ORDER BY time DESC NULLS LAST), weekly_new_bug AS (SELECT cw.start_of_week AS week, CASE WHEN NOT bug_count IS NULL THEN bug_count ELSE 0 END AS weekly_new_bug FROM calendar_weeks AS cw LEFT JOIN created_bugs AS cb ON cw.start_of_week = cb.time), weekly_closed_bug AS (SELECT cw.start_of_week AS week, CASE WHEN NOT bug_count IS NULL THEN bug_count ELSE 0 END AS weekly_closed_bug FROM calendar_weeks AS cw LEFT JOIN resolved_bugs AS cb ON cw.start_of_week = cb.time), weekly_updates AS (SELECT t1.week, weekly_new_bug, weekly_closed_bug FROM weekly_new_bug AS t1 LEFT JOIN weekly_closed_bug AS t2 ON t1.week = t2.week UNION SELECT t1.week, weekly_new_bug, weekly_closed_bug FROM weekly_new_bug AS t1 RIGHT JOIN weekly_closed_bug AS t2 ON t1.week = t2.week), original_open_bugs AS (SELECT COUNT(DISTINCT i.id) AS original_open_bug_count FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND i.status <> 'REJECTED' AND i.created_date < $__timeFrom() AND (i.status <> 'DONE' OR $__timeFilter(i.resolution_date)) AND ('${board_id:csv}' = '' OR b.id::text = ANY(ARRAY[${board_id:singlequote}]::text[]))), weekly_updated_without_null AS (SELECT week, COALESCE(weekly_new_bug, 0) AS weekly_new_bug, COALESCE(weekly_closed_bug, 0) AS weekly_closed_bug, original_open_bug_count FROM weekly_updates, original_open_bugs WHERE NOT week IS NULL), weekly_delta AS (SELECT *, (weekly_new_bug - weekly_closed_bug) AS weekly_delta FROM weekly_updated_without_null ORDER BY week ASC NULLS FIRST), final_data AS (SELECT *, TO_CHAR(CAST(week AS TIMESTAMP), 'MM/DD') || ' - ' || TO_CHAR(CAST(week + INTERVAL '7 DAY' AS TIMESTAMP), 'MM/DD') AS _week, SUM(weekly_delta) OVER (ORDER BY week ASC NULLS FIRST) AS weekly_accumulated FROM weekly_delta) SELECT _week, (original_open_bug_count + weekly_accumulated) AS \"Total No. of Outstanding Bugs By the End of Week\" FROM final_data"
    }
   ]
  },
  { "title": "Detailed Bug Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Last Week's New Bug Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT i.id) AS \"New Bugs\" FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND i.status <> 'REJECTED' AND ('${board_id:csv}' = '' OR b.id::text = ANY(ARRAY[${board_id:singlequote}]::text[])) AND i.created_date BETWEEN TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0)) - INTERVAL '1 DAY' * ((EXTRACT(ISODOW FROM TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0))) - 1) + 7) AND TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0)) - (EXTRACT(ISODOW FROM TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0))) - 1) * INTERVAL '1 day'"
    }
   ]
  },
  {
   "title": "Last Week's New Bug Count by Priority",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT priority, COUNT(DISTINCT i.id) AS \"Issue Number\" FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND i.status <> 'REJECTED' AND ('${board_id:csv}' = '' OR b.id::text = ANY(ARRAY[${board_id:singlequote}]::text[])) AND i.created_date BETWEEN TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0)) - INTERVAL '1 DAY' * ((EXTRACT(ISODOW FROM TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0))) - 1) + 7) AND TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0)) - (EXTRACT(ISODOW FROM TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0))) - 1) * INTERVAL '1 day' GROUP BY 1"
    }
   ]
  },
  {
   "title": "Last Week's New Bugs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT i.issue_key AS \"Issue Number\", i.title AS \"Title\", i.url AS \"Url\", i.creator_name AS \"Creator\" FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND i.status <> 'REJECTED' AND ('${board_id:csv}' = '' OR b.id::text = ANY(ARRAY[${board_id:singlequote}]::text[])) AND i.created_date BETWEEN TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0)) - INTERVAL '1 DAY' * ((EXTRACT(ISODOW FROM TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0))) - 1) + 7) AND TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0)) - (EXTRACT(ISODOW FROM TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0))) - 1) * INTERVAL '1 day'"
    }
   ]
  },
  {
   "title": "Last Week's Fixed Bugs Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT i.id) AS \"Fixed Bugs\" FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND status = 'DONE' AND i.status <> 'REJECTED' AND ('${board_id:csv}' = '' OR b.id::text = ANY(ARRAY[${board_id:singlequote}]::text[])) AND i.resolution_date BETWEEN TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0)) - INTERVAL '1 DAY' * ((EXTRACT(ISODOW FROM TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0))) - 1) + 7) AND TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0)) - (EXTRACT(ISODOW FROM TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0))) - 1) * INTERVAL '1 day'"
    }
   ]
  },
  {
   "title": "Average Lead Time of Last Week's Resolved Bugs in Days",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(CAST(lead_time_minutes AS NUMERIC) / NULLIF(1440, 0)) AS \"Avg Lead Time (days)\" FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND status = 'DONE' AND i.status <> 'REJECTED' AND ('${board_id:csv}' = '' OR b.id::text = ANY(ARRAY[${board_id:singlequote}]::text[])) AND i.resolution_date BETWEEN TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0)) - INTERVAL '1 DAY' * ((EXTRACT(ISODOW FROM TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0))) - 1) + 7) AND TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0)) - (EXTRACT(ISODOW FROM TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0))) - 1) * INTERVAL '1 day'"
    }
   ]
  },
  {
   "title": "Last Week's Fixed Bugs",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT i.issue_key AS \"Issue Number\", i.title AS \"Title\", CAST(lead_time_minutes AS NUMERIC) / NULLIF(1440, 0) AS \"Lead Time in Days\", i.url AS \"Url\" FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND status = 'DONE' AND i.status <> 'REJECTED' AND ('${board_id:csv}' = '' OR b.id::text = ANY(ARRAY[${board_id:singlequote}]::text[])) AND i.resolution_date BETWEEN TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0)) - INTERVAL '1 DAY' * ((EXTRACT(ISODOW FROM TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0))) - 1) + 7) AND TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0)) - (EXTRACT(ISODOW FROM TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0))) - 1) * INTERVAL '1 day'"
    }
   ]
  },
  {
   "title": "Top 10 Issue Lead Time [Last Week's Resolved Bugs in Days]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT '#' || i.issue_key || ' ' || i.title AS issue_key, CAST(lead_time_minutes AS NUMERIC) / NULLIF(1440, 0) AS lead_time FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND status = 'DONE' AND i.status <> 'REJECTED' AND ('${board_id:csv}' = '' OR b.id::text = ANY(ARRAY[${board_id:singlequote}]::text[])) AND i.resolution_date BETWEEN TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0)) - INTERVAL '1 DAY' * ((EXTRACT(ISODOW FROM TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0))) - 1) + 7) AND TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0)) - (EXTRACT(ISODOW FROM TO_TIMESTAMP(CAST($__to AS NUMERIC) / NULLIF(1000, 0))) - 1) * INTERVAL '1 day' ORDER BY lead_time DESC NULLS LAST LIMIT 10"
    }
   ]
  },
  {
   "title": "Total Number of Outstanding Bugs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT i.id) AS \"Outstanding Bugs\" FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND NOT i.status IN ('DONE', 'REJECTED') AND ('${board_id:csv}' = '' OR b.id::text = ANY(ARRAY[${board_id:singlequote}]::text[]))"
    }
   ]
  },
  {
   "title": "Average Age of Outstanding Bugs in Days",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(CAST(((EXTRACT(EPOCH FROM (NOW() - i.created_date))/60)) AS NUMERIC) / NULLIF(1440, 0)) AS \"Avg Age (days)\" FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND NOT i.status IN ('DONE', 'REJECTED') AND ('${board_id:csv}' = '' OR b.id::text = ANY(ARRAY[${board_id:singlequote}]::text[]))"
    }
   ]
  },
  {
   "title": "Outstanding Bugs Sort by Queue Time [All History]",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "rawSql": "SELECT i.issue_key AS \"Issue Number\", i.title AS \"Title\", priority AS \"Priority\", severity AS \"Severity\", CAST(((EXTRACT(EPOCH FROM (NOW() - i.created_date))/60)) AS NUMERIC) / NULLIF(1440, 0) AS \"Queue Time in Days\", i.url AS \"Url\" FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND NOT i.status IN ('DONE', 'REJECTED') AND ('${board_id:csv}' = '' OR b.id::text = ANY(ARRAY[${board_id:singlequote}]::text[])) AND ('${priority:csv}' = '' OR priority::text = ANY(ARRAY[${priority:singlequote}]::text[])) ORDER BY 'Queue Time' DESC NULLS LAST"
    }
   ]
  },
  {
   "title": "Top 100 Bug Queue Time in Days [Outstanding Bugs]",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "rawSql": "SELECT '#' || i.issue_key AS issue_key, CAST(((EXTRACT(EPOCH FROM (NOW() - i.created_date))/60)) AS NUMERIC) / NULLIF(1440, 0) AS \"Queue Time in Days\" FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND NOT i.status IN ('DONE', 'REJECTED') AND ('${board_id:csv}' = '' OR b.id::text = ANY(ARRAY[${board_id:singlequote}]::text[])) ORDER BY 2 DESC NULLS LAST LIMIT 100"
    }
   ]
  },
  {
   "title": "Bugs to be Triaged Sort by Queue Time [All History]",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "rawSql": "SELECT i.issue_key AS \"Issue Number\", i.title AS \"Title\", priority AS \"Priority\", severity AS \"Severity\", CAST(((EXTRACT(EPOCH FROM (NOW() - i.created_date))/60)) AS NUMERIC) / NULLIF(1440, 0) AS \"Queue Time in Days\", i.url AS \"Url\" FROM issues AS i JOIN board_issues AS bi ON i.id = bi.issue_id JOIN boards AS b ON bi.board_id = b.id WHERE ('${issue_type:csv}' = '' OR i.type::text = ANY(ARRAY[${issue_type:singlequote}]::text[])) AND NOT i.status IN ('DONE', 'REJECTED') AND i.assignee_name = '' AND ('${board_id:csv}' = '' OR b.id::text = ANY(ARRAY[${board_id:singlequote}]::text[])) ORDER BY 'Queue Time' DESC NULLS LAST"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 76 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/UserManuals/Dashboards/GrafanaUserGuide)."
   },
   "targets": [
    {}
   ]
  }
 ]
}